### PR TITLE
Merge Relay 1.7.0.rc-1 into persisted queries branch. Rename queryId to documentId

### PR DESCRIPTION
**Pull request by johntran**
Changes:
- Replaced all instances of `queryId` with `documentId` only in files that the persisted query PR adds. There seems to be other uses of `queryId` but I think its used in regards to Relay caching.
- Merged latest `master` branch.
  - I noticed that `RelayFileWriter.js` now exports a function and not a `RelayFileWriter` class. So I made `writeCompleteQueryMap` a function and had the new `writeAll` function call it.
- Updated tests
  - `writeRelayGeneratedFile` function does not take in `relayRuntimeModule` as a parameter anymore, so I removed it from the tests.
  - All test passes but console errors are thrown. Not sure if its relevant.
  - Did `npx flow` and `npm run lint` and no errors appear

Let me know if you need anything!

### CODE REVIEW

**Comment by alloy** [comment]
@johntran Thanks for all that work!

As for merge/rebase, it looks like you indeed merged master, instead of rebasing the persisted query changes on top of master. In retrospect, I also think it will be impossible for anybody without direct access to the branch that @yusinto PR’ed his changes from to do the full and proper squash. What you could do is:

* Take @yusinto’s branch, squash all his commits into a single commit. (I’m unfamiliar with this tutorial, but at a glance it seems to explain the process well https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history).
* Rebase that single commit on top of upstream master, such that the persisted query commit is the last one in the commit list of the branch.
* Cherry-pick your commits on top of that.
* PR like that so @yusinto can properly review the changes between his and yours.
* Then @yusinto can overwrite his PR’ed branch with your new up-to-date one, after also squashing your new commits into his 1 commit.

Phew, it’s a lot indeed. Let me know if you get stuck and I’ll see if I can find some time to do it, unless @yusinto already finds time in-between.

**Comment by alloy** [comment]
(For context, my suggestion to always squash is because when FB merges a PR into upstream Relay, their tooling will _always_ squash changes into a single commit, and in the meantime maintaining the branch will be easier when you only need to rebase 1 commit.)

**Comment by soneymathew** [comment]
@johntran , @alloy , @yusinto 
I squashed the commits from all 3 of you into one
https://github.com/facebook/relay/compare/master...soneymathew:soney/yusinto_alloy_johntran_squashed?expand=1

This is also rebased to facebook/relay master branch

Please test before using, I am looking forward to getting this merged asap as well. 
I compared this to `jt/persistedQueries-documentId-sep15` branch to verify

Please test once and let me know if this is useful.

**Comment by johntran** [comment]
@soneymathew I have merged this into `jt/persistedQueries-documentId-sep15`. Thank you for this :)

**Comment by yusinto** [comment]
Merged thanks guys!

**Comment by soneymathew** [comment]
Thanks for merging the changes @yusinto .
I think you still have to squash the commits so that, the pull request between your branch and the master branch show up as a single commit.

https://github.com/facebook/relay/compare/master...yusinto:persisted-queries should show up as a single commit
like
https://github.com/facebook/relay/compare/master...soneymathew:soney/yusinto_alloy_johntran_squashed

**Comment by soneymathew** [comment]
@yusinto  This could be a pain for the first time :) some steps to help you out
1. first step
`git clone git@github.com:yusinto/relay.git`
`cd relay`
 keep a backup
 again keep a backup :)
2. Configure a remote -> [refer](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
  `git remote add upstream https://github.com/facebook/relay.git`
3. Sync your fork to master -> [refer](https://help.github.com/articles/syncing-a-fork/)
  `git fetch upstream`
  `git checkout persisted-queries`
4. Interactive rebase -> [refer 1](https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/) & [refer 2](https://robots.thoughtbot.com/autosquashing-git-commits)
  `git rebase upstream/master --interactive --autosquash`
4.1 pick first, squash rest
image
4.2 -> 4.10 resolve conflicts manually ;) and
`git rebase --continue` until all conflicts are resolved
  The conflicts are primarily in 3 files `RelayCompilerBin.js`,`RelayFileWriter.js` and `writeRelayGeneratedFile.js`
if all the conflicts resolution is getting on your nerves
short cut -> use the content of the latest file version and overwrite, as that is the latest state you want to be at.
5. compare the outcome with a golden copy that you have as backup from step 1
6. amend the commit message to have a concise description as desired
6. `git push`
7. verify https://github.com/facebook/relay/compare/master...yusinto:persisted-queries should show up as a single commit, similar to https://github.com/facebook/relay/compare/master...soneymathew:soney/yusinto_alloy_johntran_squashed

**Pull request merged**
